 pipeline {
    agent any
    tools {
        maven 'maven'  // Asegúrate de que 'maven' esté configurado en Jenkins
        jdk 'JDK17'    // Asegúrate de que 'JDK17' esté configurado en Jenkins
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('vianeyfloresDockerhub')
        DOCKER_IMAGE = 'vianeyflores/practica5modulo5:$TAG'
    }
    stages {
        stage('Build') {
            steps {
                sh 'sudo docker build -t ${DOCKER_IMAGE} .'
            }
        }
        stage('Login & Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'vianeyfloresDockerhub', usernameVariable: 'DOCKERHUB_CREDENTIALS_USR', passwordVariable: 'DOCKERHUB_CREDENTIALS_PSW')]) {
                    sh '''
                        echo $DOCKERHUB_CREDENTIALS_PSW | sudo docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin docker.io
                        sudo docker push ${DOCKER_IMAGE}
                    '''
                }
            }
        }
        stage('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "JAVA_HOME = ${JAVA_HOME}"
                    echo "M2_HOME = ${M2_HOME}"
                    java -version
                    echo "** starting notificaciones compilation"
                    mvn clean package
                    echo "** end notificaciones compilation"
                '''
            }
        }
    }
}
